"""
Django settings for eoj3 project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

try:
  from .local_settings import *
except ImportError:
  logging.basicConfig(level=logging.INFO)
  logging.info("Now use default settings.")
  SECRET_KEY = 'd#w%dw^4lzdqn8g*2=r^yg3b3#qgq$g8%ipa+4xnjutj39_xi='
  DEBUG = True
  DATABASES = {
    'default': {
      'ENGINE': 'django.db.backends.sqlite3',
      'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
      'OPTIONS': {
        'timeout': 15000,
      }
    }
  }
  SITE_ID = 1
  ADMIN_LIST = []
  WHITE_LIST_HOST = ["127.0.0.1", ]
  RUNNER_CONFIG = {
    "cpp": {
      "compiler_file": "/usr/bin/g++",
      "compiler_args": ["-O2", "-std=c++11", '-o', "foo", "foo.cc", "-DONLINE_JUDGE", "-lm",
                        "-fmax-errors=3"],
      "code_file": "foo.cc",
      "execute_file": "foo",
    },
    "cc14": {
      "compiler_file": "/usr/bin/g++",
      "compiler_args": ["-O2", "-std=c++14", '-o', "foo", "foo.cc", "-DONLINE_JUDGE", "-lm",
                        "-fmax-errors=3"],
      "code_file": "foo.cc",
      "execute_file": "foo",
    },
    "java": {
      "compiler_file": "/usr/bin/javac",
      "compiler_args": ["-encoding", "utf8", "Main.java"],
      "code_file": "Main.java",
      "execute_file": "/usr/bin/java",
      "execute_args": ["-Xss1M", "-XX:MaxPermSize=16M", "-XX:PermSize=8M", "-Xms16M", "-Xmx{max_memory}M",
                       "-Dfile.encoding=UTF-8", "Main"],
    },
    "python": {
      "compiler_file": "/usr/bin/python3",
      "compiler_args": ["-m", "py_compile", "foo.py"],
      "code_file": "foo.py",
      "execute_file": "/usr/bin/python3",
      "execute_args": ["foo.py"]
    }
  }
  REPO_DIR = os.path.join(BASE_DIR, "repo")
  TESTDATA_DIR = os.path.join(BASE_DIR, "data")

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'django.contrib.humanize',
  'django.contrib.sites',

  'accounts',
  'backstage',
  'commons',
  'contests',
  'museum',
  'problems',
  'shares',

  # third-party packages
  'widget_tweaks',
  'django_jinja',
  'tagging',
  'debug_toolbar',
  'captcha',
  'rest_framework',
  'django_extensions',
  'django_comments_xtd',
  'django_comments',
  'notifications',
]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
  'utils.middleware.close_site_middleware.CloseSiteMiddleware',
  'debug_toolbar.middleware.DebugToolbarMiddleware',
  'utils.middleware.globalrequestmiddleware.GlobalRequestMiddleware',
  'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'eoj3.urls'

WSGI_APPLICATION = 'eoj3.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    'OPTIONS': {
      'min_length': 6
    }
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  }
]

CACHES = {
  "default": {
    "BACKEND": "django_redis.cache.RedisCache",
    "LOCATION": "redis://127.0.0.1:6379/1",
    "OPTIONS": {
      "CLIENT_CLASS": "django_redis.client.DefaultClient",
      "MAX_ENTRIES": 65536,
    }
  },
  "judge": {
    "BACKEND": "django_redis.cache.RedisCache",
    "LOCATION": "redis://127.0.0.1:6379/2",
    "OPTIONS": {
      "CLIENT_CLASS": "django_redis.client.DefaultClient",
      "MAX_ENTRIES": 65536,
    }
  }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

LANGUAGES = (
  ('zh-Hans', '简体中文'),
  ('en', 'English')
)

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/fake/static/'
STATICFILES_DIRS = []

# my settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'accounts.User'
SESSION_COOKIE_AGE = 1209600  # default 2 weeks
LOGIN_URL = '/login/'
UPLOAD_DIR = os.path.join(BASE_DIR, "upload")
MIRROR_DIR = os.path.join(BASE_DIR, "upload/mirror")
GENERATE_DIR = os.path.join(BASE_DIR, "generate")
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
DATETIME_FORMAT = 'Y-m-d H:i'  # only for django templates
DATETIME_FORMAT_TEMPLATE = '%Y-%m-%d %H:%M:%S'

# modified
TIME_ZONE = 'Asia/Shanghai'
# TIME_ZONE = 'UTC'
USE_L10N = False
USE_TZ = False

REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework.authentication.BasicAuthentication',
    'utils.authentication.UnsafeSessionAuthentication',
  )
}

INTERNAL_IPS = ('127.0.0.1',)

DEBUG_TOOLBAR_PANELS = [
  'debug_toolbar.panels.versions.VersionsPanel',
  'debug_toolbar.panels.timer.TimerPanel',
  'debug_toolbar.panels.settings.SettingsPanel',
  'debug_toolbar.panels.headers.HeadersPanel',
  'debug_toolbar.panels.request.RequestPanel',
  'debug_toolbar.panels.sql.SQLPanel',
  'debug_toolbar.panels.staticfiles.StaticFilesPanel',
  'utils.debug.TemplatesPanel',  # original broken by django-jinja, remove this whole block later
  'debug_toolbar.panels.cache.CachePanel',
  'debug_toolbar.panels.signals.SignalsPanel',
  'debug_toolbar.panels.logging.LoggingPanel',
  'debug_toolbar.panels.redirects.RedirectsPanel',
]

# captcha
CAPTCHA_FOREGROUND_COLOR = "#001100"
CAPTCHA_FILTER_FUNCTIONS = []
CAPTCHA_CHALLENGE_FUNCT = 'eoj3.captcha.random_math_challenge'

# comment
COMMENTS_APP = 'django_comments_xtd'
COMMENTS_XTD_MAX_THREAD_LEVEL = 5
COMMENTS_XTD_CONFIRM_EMAIL = False

COMMENTS_XTD_APP_MODEL_OPTIONS = {
  'default': {
    'allow_flagging': True,
    'allow_feedback': True,
    'show_feedback': False,
  },
  'contests.contests': {
    'allow_flagging': False,
    'allow_feedback': False,
    'show_feedback': False,
  }
}

COMMENT_MAX_LENGTH = 3000

# notification
NOTIFICATIONS_SOFT_DELETE = True

AUTHENTICATION_BACKENDS = ['accounts.permissions.UsernameOrEmailModelBackend']

Q_CLUSTER = {
  'name': 'eoj_cluster',
  'workers': 24,
  'recycle': 20,
  'timeout': 14400,  # 4 hours
  'retry': None,
  'cached': 3600,
  'queue_limit': 3000,
  'cpu_affinity': 1,
  'django_redis': 'default',
  'log_level': 'WARNING',
}
